import React, { useMemo, useState } from 'react';
import { MapContainer, Marker, Polyline, Popup, TileLayer } from 'react-leaflet';
import L from 'leaflet';
import { Plane, Search, Signal, Wind } from 'lucide-react';
import { FlightRecord } from '../types';
import '../flight-map.css';

const flights: FlightRecord[] = [
  { flightNumber: 'AA123', origin: 'JFK', destination: 'LHR', aircraft: 'Boeing 787', status: 'En Route', lastUpdated: '18 sec ago', altitude: 37000, speed: 542, latitude: 51.2, longitude: -19.4, path: [[40.6,-73.7],[47.2,-43.1],[51.2,-19.4],[51.4,-0.4]] },
  { flightNumber: 'BA249', origin: 'LHR', destination: 'DEL', aircraft: 'Airbus A350', status: 'Boarding', lastUpdated: '34 sec ago', altitude: 0, speed: 0, latitude: 51.4, longitude: -0.4, path: [[51.4,-0.4],[48.8,20.4],[28.5,77.1]] },
  { flightNumber: 'EK202', origin: 'DXB', destination: 'JFK', aircraft: 'Airbus A380', status: 'Scheduled', lastUpdated: '2 min ago', altitude: 0, speed: 0, latitude: 25.2, longitude: 55.3, path: [[25.2,55.3],[40.6,-73.7]] },
  { flightNumber: 'SQ12', origin: 'SIN', destination: 'NRT', aircraft: 'Boeing 777', status: 'Delayed', lastUpdated: '5 min ago', altitude: 0, speed: 0, latitude: 1.3, longitude: 103.9, path: [[1.3,103.9],[35.7,139.7]] },
];
const planeIcon = L.divIcon({ className: 'plane-marker', html: '<span class="plane-marker-core">✈</span>', iconSize: [38, 38], iconAnchor: [19, 19] });

export function FlightPage() {
  const [query, setQuery] = useState(''); const [selected, setSelected] = useState(flights[0]);
  const visible = useMemo(() => flights.filter((flight) => !query || flight.flightNumber.toLowerCase().includes(query.toLowerCase()) || flight.origin.toLowerCase().includes(query.toLowerCase()) || flight.destination.toLowerCase().includes(query.toLowerCase())), [query]);
  return <div className="page-content"><header className="page-header"><div><span className="eyebrow-label">Operations</span><h1>Flight Tracker</h1></div><div className="flight-search"><Search size={16} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search AA100, BA249..." /></div></header><div className="flight-layout"><section className="flight-left"><div className="panel-heading"><div><span className="eyebrow-label">Live telemetry</span><h2>Active flights</h2></div><span className="live-indicator"><i />Live</span></div><div className="flight-table-wrap"><table><thead><tr><th>Flight</th><th>Route</th><th>Aircraft</th><th>Status</th><th>Updated</th></tr></thead><tbody>{visible.map((flight) => <tr key={flight.flightNumber} className={selected.flightNumber === flight.flightNumber ? 'selected-row' : ''} onClick={() => setSelected(flight)}><td><strong>{flight.flightNumber}</strong></td><td>{flight.origin} <span>→</span> {flight.destination}</td><td>{flight.aircraft}</td><td><span className={`flight-status ${flight.status.toLowerCase().replace(' ', '-')}`}>{flight.status}</span></td><td>{flight.lastUpdated}</td></tr>)}</tbody></table></div><div className="selected-flight"><div className="selected-flight-top"><div><span className="eyebrow-label">Selected flight</span><h2>{selected.flightNumber} <span>{selected.origin} → {selected.destination}</span></h2></div><Plane size={26} className="text-brand" /></div><div className="telemetry-grid"><div><span>Altitude</span><strong>{selected.altitude.toLocaleString()} ft</strong></div><div><span>Ground speed</span><strong>{selected.speed} kt</strong></div><div><span>Latitude</span><strong>{selected.latitude.toFixed(2)}°</strong></div><div><span>Longitude</span><strong>{selected.longitude.toFixed(2)}°</strong></div></div></div></section><section className="map-panel"><div className="map-toolbar"><span><Signal size={15} /> Route visualization</span><span><Wind size={14} /> {selected.aircraft}</span></div><MapContainer center={[30, 0]} zoom={2} scrollWheelZoom><TileLayer attribution="&copy; OpenStreetMap contributors" url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png" /><Polyline positions={selected.path} pathOptions={{ color: '#64b5f6', weight: 3, dashArray: '8 10' }} /><Marker position={[selected.latitude, selected.longitude]} icon={planeIcon}><Popup>{selected.flightNumber} · {selected.status}</Popup></Marker></MapContainer></section></div></div>;
}
