import React, { useState } from 'react';
import { Bell, Check, Database, Moon, ShieldCheck, SlidersHorizontal } from 'lucide-react';

export function SettingsPage() {
  const [streaming, setStreaming] = useState(true); const [telemetry, setTelemetry] = useState(true);
  return <div className="page-content settings-page"><header className="page-header"><div><span className="eyebrow-label">Workspace</span><h1>Settings</h1><p>Configure how MAIA responds, connects, and keeps you informed.</p></div></header><div className="settings-grid"><section className="settings-panel"><div className="settings-title"><SlidersHorizontal size={18} /><div><h2>Response behavior</h2><p>Control the orchestration experience.</p></div></div><SettingRow icon={<Moon size={17} />} title="Dark mode" description="MAIA stays focused in a dark-only workspace." control={<span className="fixed-value">Always on</span>} /><SettingRow icon={<Database size={17} />} title="Streaming responses" description="Reveal agent output progressively as it arrives." control={<Toggle checked={streaming} onChange={() => setStreaming(!streaming)} />} /><SettingRow icon={<Bell size={17} />} title="Execution notifications" description="Show completion and error messages as toasts." control={<Toggle checked={telemetry} onChange={() => setTelemetry(!telemetry)} />} /></section><section className="settings-panel"><div className="settings-title"><ShieldCheck size={18} /><div><h2>System & privacy</h2><p>Connection and data handling.</p></div></div><SettingRow icon={<Database size={17} />} title="Backend endpoint" description="FastAPI orchestration service." control={<span className="fixed-value">localhost:8000</span>} /><SettingRow icon={<ShieldCheck size={17} />} title="Local fallback" description="Simulated responses activate when the API is offline." control={<span className="verified"><Check size={14} /> Enabled</span>} /></section></div></div>;
}
function Toggle({ checked, onChange }: { checked: boolean; onChange: () => void }) { return <button className={`toggle ${checked ? 'checked' : ''}`} onClick={onChange} aria-pressed={checked}><span /></button>; }
function SettingRow({ icon, title, description, control }: { icon: React.ReactNode; title: string; description: string; control: React.ReactNode }) { return <div className="setting-row"><div className="setting-icon">{icon}</div><div className="setting-copy"><strong>{title}</strong><span>{description}</span></div>{control}</div>; }
